$(PYTHON_DIR)/vendor-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
============================= test session starts ==============================
platform sunos5 -- Python $(PYTHON_VERSION).X -- $(PYTHON)
cachedir: .pytest_cache
rootdir: $(@D)
configfile: setup.cfg
asyncio: mode=strict, default_loop_scope=None
collecting ... collected 34 items

tests/test_timeout.py::test_timeout PASSED
tests/test_timeout.py::test_timeout_finish_in_time PASSED
tests/test_timeout.py::test_timeout_disable PASSED
tests/test_timeout.py::test_timeout_is_none_no_schedule PASSED
tests/test_timeout.py::test_timeout_no_loop PASSED
tests/test_timeout.py::test_timeout_zero PASSED
tests/test_timeout.py::test_timeout_not_relevant_exception PASSED
tests/test_timeout.py::test_timeout_canceled_error_is_not_converted_to_timeout PASSED
tests/test_timeout.py::test_timeout_blocking_loop PASSED
tests/test_timeout.py::test_for_race_conditions PASSED
tests/test_timeout.py::test_timeout_time PASSED
tests/test_timeout.py::test_outer_coro_is_not_cancelled PASSED
tests/test_timeout.py::test_cancel_outer_coro PASSED
tests/test_timeout.py::test_timeout_suppress_exception_chain PASSED
tests/test_timeout.py::test_timeout_expired PASSED
tests/test_timeout.py::test_timeout_expired_as_function SKIPPED (Old...)
tests/test_timeout.py::test_timeout_expired_methods SKIPPED (Old ver...)
tests/test_timeout.py::test_timeout_inner_timeout_error PASSED
tests/test_timeout.py::test_timeout_inner_other_error PASSED
tests/test_timeout.py::test_timeout_at PASSED
tests/test_timeout.py::test_timeout_at_not_fired PASSED
tests/test_timeout.py::test_expired_after_rejecting PASSED
tests/test_timeout.py::test_reject_finished PASSED
tests/test_timeout.py::test_expired_after_timeout PASSED
tests/test_timeout.py::test_deadline PASSED
tests/test_timeout.py::test_async_timeout PASSED
tests/test_timeout.py::test_async_no_timeout PASSED
tests/test_timeout.py::test_shift PASSED
tests/test_timeout.py::test_shift_nonscheduled PASSED
tests/test_timeout.py::test_shift_negative_expired PASSED
tests/test_timeout.py::test_shift_by_expired PASSED
tests/test_timeout.py::test_shift_to_expired PASSED
tests/test_timeout.py::test_shift_by_after_cm_exit PASSED
tests/test_timeout.py::test_enter_twice PASSED


======== 32 passed, 2 skipped ========
